; ==========================
; PHP custom configuration
; ==========================

; Thời gian sống của session (30 phút)
session.gc_maxlifetime = 1800

; Dùng Redis làm nơi lưu session
session.save_handler = redis
session.save_path = "tcp://redis:6379"

; Đặt tên session (tùy chọn)
session.name = MYSESSIONID

; Hiển thị lỗi khi debug (bạn có thể tắt sau này)
display_errors = On
error_reporting = E_ALL
